<ips:template parameters="$comment, $email" />
<tr style='border-bottom: 1px solid #eeeeee'>
	<td dir='{dir}' width='120' align='center' valign='top'>
		{{if $comment->item()->primary_screenshot_thumb}}
			<img src='{$comment->item()->primary_screenshot_thumb}' style='border: 1px solid #000; vertical-align: middle;' width='100' height='100'>
		{{else}}
			<div style='width: 100px; height: 100px; background: #f5f5f5'>&nbsp;</div>
		{{endif}}
	</td>
	<td dir='{dir}' align='left'>
		<p style='font-family: "Helvetica Neue", helvetica, sans-serif; margin: 0; font-size: 13px; font-weight: bold'>
			{$email->language->addToStack("x_commented_file", FALSE, array( 'sprintf' => array( $comment->author()->name ) ) )}
		</p>
		<h2 style="font-family: 'Helvetica Neue', helvetica, sans-serif; font-size: 15px; font-weight: 500 !important; margin: 0;">
			<a href='{$comment->item()->url()}' style='text-decoration: none;'>{$comment->item()->name}</a>
		</h2>
		<div style='font-family: "Helvetica Neue", helvetica, sans-serif; line-height: 22px; margin-top: 5px; margin-bottom: 5px; border-left: 3px solid #8c8c8c; padding-left: 15px; font-size: 14px; margin-left: 15px'>
			{$email->parseTextForEmail( $comment->content(), $email->language )|raw}
		</div>
	</td>
</tr>