<ips:template parameters="" />

<div class="ipsPad">
	<h2 class="ipsFieldRow_section">DCU Bitracker 1.0.0</h2>

		<div class="ipsPad">New! Full featured bit torrent tracker application for IPS 4.2x/4.3x Community Suite.</div>


	<h2 class="ipsFieldRow_section">Support/License</h2>
	<div class="ipsPad">Support available directly from devCU forums issue tracker. You can get the latest source from GitHub. </div>
	<h2 class="ipsFieldRow_section">Project Links</h2>
	<div class="ipsPad"><a href="https://www.devcu.com" target="_blank">devCU Software</a> <br></div>

</div>