<ips:template parameters="" />

<div class='ipsColumns ipsColumns_collapsePhone'>
	<div class='ipsColumn ipsColumn_fluid'>
		<ul class='ipsDataList'>
			<li class='ipsDataItem'>
				<div class='ipsDataItem_main'>
					<h3 class='ipsType_sectionHead'><strong>{lang="system_bitracker_info"}</strong></h3><br><br>
			{{if \IPS\Settings::i()->bit_announce_enable}}
                     <a class="ipsBadge ipsBadge_positive" href="#"> {lang="system_bitracker_enabled"} </a> <strong>{lang="system_private_tracker"}</strong> <i class="fa fa-question-circle" aria-hidden="true" data-ipsTooltip title="{lang="system_private_tracker_enabled"}"></i><br><br>
            {{else}}
                     <a class="ipsBadge ipsBadge_negative" href="#"> {lang="system_bitracker_disabled"} </a> <strong>{lang="system_private_tracker"}</strong> <i class="fa fa-question-circle" aria-hidden="true" data-ipsTooltip title="{lang="system_private_tracker_disabled"}"></i><br><br>
           {{endif}}
			{{if \IPS\Settings::i()->bit_security_forcessl}}
                     <a class="ipsBadge ipsBadge_positive" href="#"> {lang="system_bitracker_enabled"} </a> <strong>{lang="system_ssl_secure"}</strong> <i class="fa fa-question-circle" aria-hidden="true" data-ipsTooltip title="{lang="system_ssl_secure_enabled"}"></i><br><br>
            {{else}}
                     <a class="ipsBadge ipsBadge_negative" href="#"> {lang="system_bitracker_disabled"} </a> <strong>{lang="system_ssl_secure"}</strong> <i class="fa fa-question-circle" aria-hidden="true" data-ipsTooltip title="{lang="system_ssl_secure_disabled"}"></i><br><br>
           {{endif}}
     <strong>{lang="system_bitracker_announceurl"}</strong> <i class="fa fa-question-circle" aria-hidden="true" data-ipsTooltip title="{lang="system_bitracker_announceurl_tip"}"></i><br><br>
    <input id='announce' type='text' value='{expression="\IPS\Settings::i()->bit_announce_url"}' readonly>
    <button class="ann ipsButton ipsButton_link" data-clipboard-action="copy" data-clipboard-target="#announce" data-ipsTooltip title="Copy to clipboard">Copy</button>

				</div>
			</li>
			<li class='ipsDataItem'>
				<div class='ipsDataItem_main'>
						<a href="{url="app=bitracker&module=system&controller=settings&area=ipaddress" seoTemplate="bitracker_ipaddress"}" class="ipsButton ipsButton_link ipsPos_right">{lang="Update"}</a>
					<h3 class='ipsType_sectionHead'><strong>{lang="system_current_ipaddress"}</strong></h3><br><br>
					<strong>{member="ip_address"}</strong>
				</div>
			</li>
			<li class='ipsDataItem'>
				<div class='ipsDataItem_main'>
						<a href="{url="app=bitracker&module=system&controller=settings&area=configure" seoTemplate="bitracker_configure"}" class="ipsButton ipsButton_link ipsPos_right">{lang="Change"}</a>
					<h3 class='ipsType_sectionHead'><strong>{lang="system_add_ipaddress"}</strong></h3><br><br>
					<strong>{member="bit_ip_address2"}</strong><br><br>
					<strong>{member="bit_ip_address3"}</strong>
				</div>
			</li>
			<li class='ipsDataItem'>
				<div class='ipsDataItem_main'>
						<a href="{url="app=bitracker&module=system&controller=settings&area=security" seoTemplate="bitracker_security"}" class="ipsButton ipsButton_link ipsPos_right">{lang="Change"}</a>
					<h3 class='ipsType_sectionHead'><strong>{lang="system_connection_security"}</strong></h3><br><br>
			{{if \IPS\Settings::i()->bit_security_permkey}}
                     <a class="ipsBadge ipsBadge_positive" href="#"> {lang="system_bitracker_enabled"} </a> <strong>{lang="Secure PassKey Access"}</strong> <i class="fa fa-question-circle" aria-hidden="true" data-ipsTooltip title="Tracker will only accept announce with unique key"></i><br><br>
            {{else}}
                     <a class="ipsBadge ipsBadge_negative" href="#"> {lang="system_bitracker_disabled"} </a> <strong>{lang="Secure PassKey Access"}</strong> <i class="fa fa-question-circle" aria-hidden="true" data-ipsTooltip title="Tracker will accept announce with no unique key"></i><br><br>
           {{endif}}
			{{if \IPS\Settings::i()->bit_security_ipenable}}
					<a class="ipsBadge ipsBadge_positive" href="#"> {lang="system_bitracker_enabled"} </a>
					{{if \IPS\Settings::i()->bit_security_bindip}}
					<a class="ipsBadge ipsBadge_neutral" href="#"> {lang="system_bitracker_forced"} </a> <strong>{lang="IP Address Bind"}</strong> <i class="fa fa-question-circle" aria-hidden="true" data-ipsTooltip title="You can only connect from IP addresses in your account"></i><br><span class='ipsFieldRow_required'>* {lang="Admin has forced Bind IP on all accounts"}</span>
					{{else}} 
					<a class="ipsBadge ipsBadge_intermediary" href="#"> {lang="system_bitracker_optional"} </a> <strong>{lang="IP Address Bind"}</strong> <i class="fa fa-question-circle" aria-hidden="true" data-ipsTooltip title="You can connect from any IP addresses in your account"></i><br><span class='ipsFieldRow_required'>* {lang="Admin has allowed optional Bind IP for members"}</span>
			        {{endif}} 
            {{else}}
                     <a class="ipsBadge ipsBadge_negative" href="#"> {lang="system_bitracker_disabled"} </a> <strong>{lang="IP Address Bind"}</strong> <i class="fa fa-question-circle" aria-hidden="true" data-ipsTooltip title="Tracker will accept any IP"></i>
           {{endif}}
				</div>
			</li>
			<li class='ipsDataItem'>
				<div class='ipsDataItem_main'>
						<a href="{url="app=bitracker&module=system&controller=settings&area=privacy" seoTemplate="bitracker_privacy"}" class="ipsButton ipsButton_link ipsPos_right">{lang="Change"}</a>
					<h3 class='ipsType_sectionHead'><strong>{lang="system_profile_privacy"}</strong></h3><br><br>
					<a class="ipsBadge ipsBadge_negative ipsBadge_large" href="#"> <strong>{lang="Public"}</strong> </a><br><span class='ipsFieldRow_required'>* {lang="Your tracker activity is viewable by all members"}</span>
				</div>
			</li>
		</ul>
	</div>
	<div class='ipsColumn ipsColumn_wide ipsAreaBackground_light'>
		<div class='ipsPad'>
			{{$thisMemberID = \IPS\Member::loggedIn()->member_id;}}
			<h3 class='ipsType_sectionHead'>{lang="other_settings"}</h3>
			<br><br>
			<ul class='ipsList ipsList_reset ipsType_medium'>
				<li><a href='{url="app=core&module=system&controller=notifications&do=options" seoTemplate="notifications_options"}'>{lang="system_notification_options"}</a></li>
			</ul>
		</div>
	</div>
</div>