<ips:template parameters="$data" />

<!-- <div class="ipsAreaBackground_light ipsPad">
				{{if \IPS\Application::appIsEnabled('bitracker')}}<strong style="font-size:20px;" class="ipsOnlineStatus ipsOnlineStatus_online"><i class="fa fa-circle"> </i> Tracker Online</strong> {{else}} <strong style="font-size:20px;" class="ipsOnlineStatus ipsOnlineStatus_offline"><i class="fa fa-circle"> </i> Tracker Offline</strong> {{endif}}
</div>
<p>
	 
</p> -->
<div class="ipsAreaBackground_light ipsPad">
	<div class="ipsGrid ipsGrid_collapsePhone">
		<div class="ipsGrid_span3 ipsPad" style="height:125px;background: #006666;">
			<span style="color: #fff; font-size:25px;"><i class="fas fa-random"></i> Transfer</span><br><br><br>
			<span style="color: #fff; font-size:45px;"> 0 </span>
		</div>

		<div class="ipsGrid_span3 ipsPad" style="height:125px;background: #6f4e77;">
			<span style="color: #fff; font-size:25px;"><i class="fas fa-cloud-download-alt"></i> Torrents</span><br><br><br>
			<span style="color: #fff; font-size:45px;"> 0 </span>
		</div>

		<div class="ipsGrid_span3 ipsPad" style="height:125px;background: #bf2e50;">
			<span style="color: #fff; font-size:25px;"><i class="fas fa-users"></i> Peers</span><br><br><br>
			<span style="color: #fff; font-size:45px;"> 0 </span>
		</div>

		<div class="ipsGrid_span3 ipsPad" style="height:125px;background: #b2b200;">
			<span style="color: #fff; font-size:25px;"><i class="far fa-hdd"></i> Disk</span><br><br><br>
			<span style="color: #fff; font-size:45px;"> 0 </span>
		</div>
	</div>
</div>

<div class="ipsAreaBackground_light ipsPad">
	<div class="ipsGrid ipsGrid_collapsePhone">
	 <div class="ipsColumns">
		<div class="ipsColumn ipsColumn_fluid ipsGrid_span12 ipsPad" style="background: #D24625; color: #fff;">
			<span style="color: #fff; font-size:20px;"><i class="fas fa-shipping-fast"></i> Active Files</span>
		</div>
	</div>
  </div>
</div>

	<p class="ipsPad ipsPos_center">{lang="no_results"}</p>

<div class="ipsAreaBackground_light ipsPad">
	<div class="ipsGrid ipsGrid_collapsePhone">
	 <div class="ipsColumns">
		<div class="ipsColumn ipsColumn_fluid ipsGrid_span12 ipsPad" style="background: #2E3D49; color: #fff;">
			<span style="color: #fff; font-size:20px;"><i class="fas fa-user-check"></i> Active Members</span>
		</div>
	</div>
  </div>
</div>

	<p class="ipsPad ipsPos_center">{lang="no_results"}</p>

<div class="ipsAreaBackground_light ipsPad">
	<div class="ipsGrid ipsGrid_collapsePhone">
	 <div class="ipsColumns">
		<div class="ipsColumn ipsColumn_fluid ipsGrid_span12 ipsPad" style="background: #3B6C99; color: #fff;">
			<span style="color: #fff; font-size:20px;"><i class="fas fa-broadcast-tower"></i> Bandwidth Usage</span>
		</div>
	</div>
  </div>
</div>

	<p class="ipsPad ipsPos_center">{lang="no_results"}</p>

<!-- <ul class="ipsDataList">
	{{foreach $data as $k => $v}}
		<li class="ipsDataItem">
			<span class="ipsDataItem_generic ipsDataItem_size6">
				<strong>{lang="$k"}</strong>
			</span>
			<span class="ipsDataItem_generic">
				{{if in_array( $k, array( 'total_disk_spaced', 'total_bandwidth', 'current_month_bandwidth' ) )}}
					{filesize="$v"}
				{{elseif $k === 'largest_file'}}
					<a href='{$v->url()}' target='_blank'>{$v->name}</a> <span class="ipsType_light">({filesize="$v->filesize()"})</span>
				{{elseif $k === 'most_viewed_file'}}
					<a href='{$v->url()}' target='_blank'>{$v->name}</a> <span class="ipsType_light">({lang="num_views_with_number" pluralize="$v->views"})</span>
				{{elseif $k === 'most_downloaded_file'}}
					<a href='{$v->url()}' target='_blank'>{$v->name}</a> <span class="ipsType_light">({lang="num_bitracker" pluralize="$v->bitracker"})</span>
				{{elseif $k === 'total_files' OR $k === 'total_views' OR $k === 'total_bitracker'}}
					{number="$v"}
				{{else}}
					{$v}
				{{endif}}
			</span>
		</li>
	{{endforeach}}
</ul>
<div class="ipsPad_half ipsType_light">
	{lang="download_stats_disclaimer"}
</div> -->