<ips:template parameters="$id, $action, $elements, $hiddenValues, $actionButtons, $uploadField, $class=''" />

<form accept-charset='utf-8' class="ipsForm" action="{$action}" method="post" {{if $uploadField}}enctype="multipart/form-data"{{endif}}>
	<input type="hidden" name="{$id}_submitted" value="1">
	{{foreach $hiddenValues as $k => $v}}
		<input type="hidden" name="{$k}" value="{$v}">
	{{endforeach}}
	{{if $uploadField}}
		<input type="hidden" name="MAX_FILE_SIZE" value="{$uploadField}">
		<input type="hidden" name="plupload" value="{expression="md5( mt_rand() )"}">
	{{endif}}
	<div class='ipsAreaBackground_light ipsPad'>
		<h2 class='ipsType_sectionHead'>{lang="write_review"}</h2>
		<ul class='ipsForm ipsForm_vertical'>
			{{foreach $elements as $collection}}
				{{foreach $collection as $input}}
					{$input|raw}
				{{endforeach}}
			{{endforeach}}
			<li class='ipsFieldRow ipsClearfix'>
				<div class='ipsFieldRow_content'>
					<button type='submit' class='ipsButton ipsButton_primary'>{lang="add_review"}</button>
				</div>
			</li>
		</ul>
	</div>
</form>