<ips:template parameters="$stats, $latestFile, $orientation='vertical'" />

<h3 class='ipsType_reset ipsWidget_title'>{lang="block_downloadStats"}</h3>
<div class='ipsWidget_inner'>
	{{if $orientation == 'vertical'}}
		<div class='ipsPad_half'>
			<ul class='ipsDataList' id='elTorrentsStats'>
				<li class='ipsDataItem'>
					<div class='ipsDataItem_main ipsPos_middle'>
						<strong>{lang="total_torrents_front"}</strong>
					</div>
					<div class='ipsDataItem_stats ipsDataItem_statsLarge'>
						<span class='ipsDataItem_stats_number'>{number="$stats['totalFiles']"}</span>
					</div>
				</li>
				{{if $stats['totalComments']}}
					<li class='ipsDataItem'>
						<div class='ipsDataItem_main ipsPos_middle'>
							<strong>{lang="total_comments"}</strong>
						</div>
						<div class='ipsDataItem_stats ipsDataItem_statsLarge'>
							<span class='ipsDataItem_stats_number'>{number="$stats['totalComments']"}</span>
						</div>
					</li>
				{{endif}}
				{{if $stats['totalReviews']}}
					<li class='ipsDataItem'>
						<div class='ipsDataItem_main ipsPos_middle'>
							<strong>{lang="total_reviews"}</strong>
						</div>
						<div class='ipsDataItem_stats ipsDataItem_statsLarge'>
							<span class='ipsDataItem_stats_number'>{number="$stats['totalReviews']"}</span>
						</div>
					</li>
				{{endif}}
			</ul>
			<hr class='ipsHr'>
			{{if $latestFile}}
				<div id='elDownloadStatsLatest' class='ipsClearfix'>
					{template="thumbImage" group="global" app="core" params="$latestFile->primary_screenshot, $latestFile->name, 'small', 'ipsPos_left'"}
					<div class='ipsWidget_latestItem'>
						<strong class='ipsType_small ipsType_uppercase'>{lang="latest_file"}</strong><br>
						<div class='ipsType_break ipsContained'><a href="{$latestFile->url()}" title='{lang="view_this_file" sprintf="$latestFile->name"}' class='ipsTruncate ipsTruncate_line'>{$latestFile->name}</a></div>
						<span class='ipsType_light ipsType_medium'>{lang="byline_nodate" htmlsprintf="$latestFile->author()->link()"}</span>
						<p class='ipsType_medium ipsType_reset'>{{if !$latestFile->bitracker}}<span class='ipsType_light'>{{endif}}<i class='fa fa-arrow-circle-down'></i> {number="$latestFile->bitracker"}{{if !$latestFile->bitracker}}</span>{{endif}} {{if $latestFile->container()->bitoptions['comments']}}&nbsp;&nbsp;{{if !$latestFile->comments}}<span class='ipsType_light'>{{endif}}<i class='fa fa-comment'></i> {$latestFile->comments}{{endif}}{{if !$latestFile->comments}}</span>{{endif}}</p>
					</div>
				</div>
			{{endif}}
		</div>
	{{else}}
		{{$columns = 2;}}
		{{$columns += ( $stats['totalComments'] ) ? 1 : 0;}}
		{{$columns += ( $stats['totalReviews'] ) ? 1 : 0;}}
		{{$span = 12 / $columns;}}
		<div class='ipsGrid ipsGrid_collapsePhone ipsWidget_stats'>
			<div class='ipsGrid_span{$span} ipsType_center cBitrackerWidget_statsNumber'>
				<span class='ipsType_large ipsWidget_statsCount'>{number="$stats['totalFiles']"}</span><br>
				<span class='ipsType_light ipsType_medium'>{lang="total_torrents_front"}</span>
			</div>
			{{if $stats['totalComments']}}
				<div class='ipsGrid_span{$span} ipsType_center cBitrackerWidget_statsNumber'>
					<span class='ipsType_large ipsWidget_statsCount'>{number="$stats['totalComments']"}</span><br>
					<span class='ipsType_light ipsType_medium'>{lang="total_comments"}</span>
				</div>
			{{endif}}
			{{if $stats['totalReviews']}}
				<div class='ipsGrid_span{$span} ipsType_center cBitrackerWidget_statsNumber'>
					<span class='ipsType_large ipsWidget_statsCount'>{number="$stats['totalReviews']"}</span><br>
					<span class='ipsType_light ipsType_medium'>{lang="total_reviews"}</span>
				</div>
			{{endif}}
			{{if $latestFile}}
				<div class='ipsGrid_span{$span} ipsType_left cNewestMember'>
					<div id='elDownloadStatsLatest' class='ipsClearfix'>
						<span class='ipsType_minorHeading'>{lang="latest_file"}</span><br>
						<div class='ipsType_break ipsContained'><a href="{$latestFile->url()}" title='{lang="view_this_file" sprintf="$latestFile->name"}' class='ipsTruncate ipsTruncate_line'>{$latestFile->name}</a></div>
						<span class='ipsType_light ipsType_medium'>{lang="byline_nodate" htmlsprintf="$latestFile->author()->link()"}</span>
						<p class='ipsType_medium ipsType_reset'>{{if !$latestFile->bitracker}}<span class='ipsType_light'>{{endif}}<i class='fa fa-arrow-circle-down'></i> {number="$latestFile->bitracker"}{{if !$latestFile->bitracker}}</span>{{endif}} {{if $latestFile->container()->bitoptions['comments']}}&nbsp;&nbsp;{{if !$latestFile->comments}}<span class='ipsType_light'>{{endif}}<i class='fa fa-comment'></i> {$latestFile->comments}{{endif}}{{if !$latestFile->comments}}</span>{{endif}}</p>
					</div>
				</div>
			{{endif}}
		</div>
	{{endif}}
</div>