<ips:template parameters="$week, $month, $year, $all, $orientation='vertical'" />

<h3 class='ipsType_reset ipsWidget_title'>{lang="block_topDownloads"}</h3>

{{if $orientation == 'vertical'}}
	<div class='ipsTabs ipsTabs_small ipsTabs_stretch ipsClearfix' id='elTorrentsTopDownloads' data-ipsTabBar data-ipsTabBar-contentArea='#elTorrentsTopDownloads_content'>
		<a href='#elTorrentsTopDownloads' data-action='expandTabs'><i class='fa fa-caret-down'></i></a>
		<ul role="tablist">
			<li>
				<a href='#ipsTabs_elTorrentsTopDownloads_elTorrents_topDownloadsWeek_panel' id='elTorrents_topDownloadsWeek' class='ipsTabs_item ipsTabs_activeItem ipsType_center' role="tab" aria-selected='true'>{lang="top_week"}</a>
			</li>
			<li>
				<a href='#ipsTabs_elTorrentsTopDownloads_elTorrents_topDownloadsMonth_panel' id='elTorrents_topDownloadsMonth' class='ipsTabs_item ipsType_center' role="tab" aria-selected='false'>{lang="top_month"}</a>
			</li>		
			<li>
				<a href='#ipsTabs_elTorrentsTopDownloads_elTorrents_topDownloadsYear_panel' id='elTorrents_topDownloadsYear' class='ipsTabs_item ipsType_center' role="tab" aria-selected='false'>{lang="top_year"}</a>
			</li>
			<li>
				<a href='#ipsTabs_elTorrentsTopDownloads_elTorrents_topDownloadsAll_panel' id='elTorrents_topDownloadsAll' class='ipsTabs_item ipsType_center' role="tab" aria-selected='false'>{lang="top_alltime"}</a>
			</li>
		</ul>
	</div>

	<section id='elTorrentsTopDownloads_content' class='ipsWidget_inner'>
		<div id="ipsTabs_elTorrentsTopDownloads_elTorrents_topDownloadsWeek_panel" class='ipsTabs_panel ipsPad_half'>
			{{if count( $week )}}
				<ol class='ipsDataList ipsDataList_reducedSpacing'>
					{{foreach $week as $idx => $data}}
						{template="fileRow" group="widgets" app="bitracker" params="$data"}
					{{endforeach}}
				</ol>
			{{else}}
				<p class='ipsType_reset'>{lang="no_downloaded_torrents__week"}</p>
			{{endif}}
		</div>
		<div id="ipsTabs_elTorrentsTopDownloads_elTorrents_topDownloadsMonth_panel" class='ipsTabs_panel ipsPad_half'>
			{{if count( $month )}}
				<ol class='ipsDataList ipsDataList_reducedSpacing'>
					{{foreach $month as $idx => $data}}
						{template="fileRow" group="widgets" app="bitracker" params="$data"}
					{{endforeach}}
				</ol>
			{{else}}
				<p class='ipsType_reset'>{lang="no_downloaded_torrents__month"}</p>
			{{endif}}
		</div>
		<div id="ipsTabs_elTorrentsTopDownloads_elTorrents_topDownloadsYear_panel" class='ipsTabs_panel ipsPad_half'>
			{{if count( $year )}}
				<ol class='ipsDataList ipsDataList_reducedSpacing'>
					{{foreach $year as $idx => $data}}
						{template="fileRow" group="widgets" app="bitracker" params="$data"}
					{{endforeach}}
				</ol>
			{{else}}
				<p class='ipsType_reset'>{lang="no_downloaded_torrents__year"}</p>
			{{endif}}
		</div>
		<div id="ipsTabs_elTorrentsTopDownloads_elTorrents_topDownloadsAll_panel" class='ipsTabs_panel ipsPad_half'>
			{{if count( $all )}}
				<ol class='ipsDataList ipsDataList_reducedSpacing'>
					{{foreach $all as $idx => $data}}
						{template="fileRow" group="widgets" app="bitracker" params="$data"}
					{{endforeach}}
				</ol>
			{{else}}
				<p class='ipsType_reset'>{lang="no_downloaded_files"}</p>
			{{endif}}
		</div>
	</section>
{{else}}
	<div class='ipsGrid ipsGrid_collapsePhone ipsWidget_columns ipsPad'>
		<div class='ipsGrid_span3'>
			<h4 class='ipsType_sectionHead ipsType_normal'>{lang="week"}</h4>

			{{if count( $week )}}
				<ol class='ipsDataList ipsDataList_reducedSpacing'>
					{{foreach $week as $idx => $data}}
						{template="fileRow" group="widgets" app="bitracker" params="$data, $orientation"}
					{{endforeach}}
				</ol>
			{{else}}
				<div class='ipsPad'>
					<p class='ipsType_reset ipsType_left ipsType_light'>{lang="no_downloaded_torrents__week"}</p>
				</div>
			{{endif}}
		</div>
		<div class='ipsGrid_span3'>
			<h4 class='ipsType_sectionHead ipsType_normal'>{lang="month"}</h4>

			{{if count( $month )}}
				<ol class='ipsDataList ipsDataList_reducedSpacing'>
					{{foreach $month as $idx => $data}}
						{template="fileRow" group="widgets" app="bitracker" params="$data, $orientation"}
					{{endforeach}}
				</ol>
			{{else}}
				<div class='ipsPad'>
					<p class='ipsType_reset ipsType_left ipsType_light'>{lang="no_downloaded_torrents__month"}</p>
				</div>
			{{endif}}
		</div>
		<div class='ipsGrid_span3'>
			<h4 class='ipsType_sectionHead ipsType_normal'>{lang="year"}</h4>

			{{if count( $year )}}
				<ol class='ipsDataList ipsDataList_reducedSpacing'>
					{{foreach $year as $idx => $data}}
						{template="fileRow" group="widgets" app="bitracker" params="$data, $orientation"}
					{{endforeach}}
				</ol>
			{{else}}
				<div class='ipsPad'>
					<p class='ipsType_reset ipsType_left ipsType_light'>{lang="no_downloaded_torrents__year"}</p>
				</div>
			{{endif}}
		</div>
		<div class='ipsGrid_span3'>
			<h4 class='ipsType_sectionHead ipsType_normal'>{lang="alltime"}</h4>

			{{if count( $all )}}
				<ol class='ipsDataList ipsDataList_reducedSpacing'>
					{{foreach $all as $idx => $data}}
						{template="fileRow" group="widgets" app="bitracker" params="$data, $orientation"}
					{{endforeach}}
				</ol>
			{{else}}
				<div class='ipsPad'>
					<p class='ipsType_reset ipsType_left ipsType_light'>{lang="no_downloaded_files"}</p>
				</div>
			{{endif}}
		</div>
	</div>
{{endif}}