<ips:template parameters="$clubsOnly=FALSE" />

<div class="ipsPageHeader ipsClearfix ipsSpacer_bottom" id='elDownloadersHeader'>
	{template="pageHeader" group="global" app="core" params="\IPS\Settings::i()->bit_application_name"}
</div>
{{if !$clubsOnly}}
	<div class='ipsBox ipsSpacer_bottom'>
		<h2 class='ipsType_sectionTitle ipsType_reset'>{lang="categories"}</h2>
		<ol class="ipsDataList ipsDataList_large">
			{template="categoryRow" group="browse" params="NULL, NULL, \IPS\bitracker\Category::roots()"}
		</ol>
	</div>
{{endif}}
{{if settings.club_nodes_in_apps and $clubNodes = \IPS\bitracker\Category::clubNodes()}}
	<div class='ipsBox'>
		<h2 class='ipsType_sectionTitle ipsType_reset'><a href="{url="app=bitracker&module=portal&controller=main&id=clubs" seoTemplate="bitracker_clubs"}">{lang="club_node_bitracker"}</a></h2>
		<ol class="ipsDataList ipsDataList_large">
			{template="categoryRow" group="browse" params="NULL, NULL, $clubNodes"}
		</ol>
	</div>
{{endif}}