<ips:template parameters="$currentCategory=NULL" />

{{if !$currentCategory or !$currentCategory->club()}}
	{{$categories = $currentCategory ? $currentCategory->children() : \IPS\bitracker\Category::roots();}}
	
	{{$clubNodes = $currentCategory ? array() : ( \IPS\Settings::i()->club_nodes_in_apps ? \IPS\bitracker\Category::clubNodes() : array() );}}
	{{if !\IPS\bitracker\Category::theOnlyNode() or $clubNodes}}
	<div id='elTorrentsCategoriesBlock' class='ipsWidget ipsWidget_vertical ipsBox'>
		<h3 class='ipsType_sectionTitle ipsType_reset'>{{if $currentCategory}}{lang="subcategories"}{{else}}{lang="categories"}{{endif}}</h3>
		<div class='ipsPad_half'>
			<div class='ipsSideMenu'>
				<ul class='ipsSideMenu_list'>
					{{foreach $categories as $category}}
						{{if $category->open OR \IPS\Member::loggedIn()->isAdmin()}}
							<li>
								<a href="{$category->url()}" class='ipsSideMenu_item ipsTruncate ipsTruncate_line'><span class='ipsBadge ipsBadge_style1 ipsPos_right cBitrackerCategoryCount'>{number="\IPS\bitracker\File::contentCount( $category )"}</span><strong class='ipsType_normal'>{$category->_title}</strong></a>
								{{if $category->hasChildren()}}
									<ul class="ipsSideMenu_list">
										{{foreach $category->children() as $idx => $subcategory}}
											{{if $subcategory->open OR \IPS\Member::loggedIn()->isAdmin()}}
												<li>
													{{if $idx >= 5}}
														<a href='{$category->url()}' class='ipsSideMenu_item'><span class='ipsType_light ipsType_small'>{lang="and_x_more" pluralize="count( $category->children() ) - 5"}</span></a>
														{{break;}}
													{{else}}
														<a href="{$subcategory->url()}" class='ipsSideMenu_item ipsTruncate ipsTruncate_line'><strong class='ipsPos_right ipsType_small cBitrackerCategoryCount'>{number="\IPS\bitracker\File::contentCount( $subcategory )"}</strong>{$subcategory->_title}</a>
													{{endif}}
												</li>
											{{endif}}
										{{endforeach}}
									</ul>
								{{endif}}
							</li>
						{{endif}}
					{{endforeach}}
					{{if $clubNodes}}
						<li>
							<a href="{url="app=bitracker&module=portal&controller=main&id=clubs" seoTemplate="bitracker_clubs"}" class='ipsSideMenu_item ipsTruncate ipsTruncate_line'><span class='ipsBadge ipsBadge_style1 ipsPos_right cBitrackerCategoryCount'>{number="\IPS\bitracker\Category::filesInClubNodes()"}</span><strong class='ipsType_normal'>{lang="club_node_bitracker"}</strong></a>
							<ul class="ipsSideMenu_list">
								{{foreach $clubNodes as $idx => $subcategory}}
									{{if $subcategory->open OR \IPS\Member::loggedIn()->isAdmin()}}
										<li>
											{{if $idx >= 5}}
												<a href='{$category->url()}' class='ipsSideMenu_item'><span class='ipsType_light ipsType_small'>{lang="and_x_more" pluralize="count( $category->children() ) - 5"}</span></a>
												{{break;}}
											{{else}}
												<a href="{$subcategory->url()}" class='ipsSideMenu_item ipsTruncate ipsTruncate_line'><strong class='ipsPos_right ipsType_small cBitrackerCategoryCount'>{number="\IPS\bitracker\File::contentCount( $subcategory )"}</strong>{$subcategory->_title}</a>
											{{endif}}
										</li>
									{{endif}}
								{{endforeach}}
							</ul>
						</li>
					{{endif}}
				</ul>
				<p class='ipsType_center'>
					<a href='{url="app=bitracker&module=portal&controller=main&do=categories" seoTemplate="bitracker_categories"}' class=''>{lang="browse_categories_d"} &nbsp;<i class='fa fa-caret-right'></i></a>
				</p>
			</div>
		</div>
	</div>
	{{endif}}
{{endif}}