<ips:template parameters="$table, $headers, $rows" />

{{foreach $rows as $row}}
	<li class="ipsDataItem ipsAreaBackground_reset {{if $row->unread()}}ipsDataItem_unread{{endif}} {{if method_exists( $row, 'tableClass' ) && $row->tableClass()}}ipsDataItem_{$row->tableClass()}{{endif}} {{if $row->hidden()}}ipsModerated{{endif}}">
		<div class='ipsDataItem_icon ipsPos_top ipsResponsive_hidePhone'>
            {template="thumb" group="global" app="bitracker" params="$row, 'tiny'"}	
		</div>
		<div class='ipsDataItem_main'>
            <h4 class='ipsDataItem_title ipsType_sectionHead'>
				{{if $row->unread()}}
					<span class='ipsItemStatus ipsItemStatus_small' data-ipsTooltip title='{{if $row->unread() === -1}}{lang="new"}{{else}}{lang="updated"}{{endif}}'><i class="fa fa-circle"></i></span>&nbsp;
				{{endif}}            
            
    			{{if $row->prefix()}}
    				{template="prefix" group="global" app="core" params="$row->prefix( TRUE ), $row->prefix()"}
    			{{endif}}
    
				<a href='{$row->url()}'>{$row->title}</a>

    			{{if $row->hidden() === -1}}
    				<span class="ipsBadge ipsBadge_icon ipsBadge_small ipsBadge_warning" data-ipsTooltip title='{$row->hiddenBlurb()}'><i class='fa fa-eye-slash'></i></span>
    			{{elseif $row->hidden() === 1}}
    				<span class="ipsBadge ipsBadge_icon ipsBadge_small ipsBadge_warning" data-ipsTooltip title='{lang="pending_approval"}'><i class='fa fa-warning'></i></span>
    			{{endif}}
                {{if $row->averageRating()}}<br>{template="rating" app="core" params="'small', $row->averageRating()" group="global"}{{endif}}<br>
		    </h4>
            
			{{if count( $row->tags() )}}
				{template="tags" group="global" app="core" params="$row->tags()"}
			{{endif}}            
        </div>

		<ul class='ipsDataItem_stats'>			
			<li>
				<span class='ipsDataItem_stats_number'>{lang="num_bitracker_comments" pluralize="$row->num_comments"}</span>				
			</li>		
			<li class='ipsType_light'>
				<span class='ipsDataItem_stats_number'>{lang="num_bitracker_views" pluralize="$row->views"}</span>
			</li>			
		</ul>

		<ul class='ipsDataItem_lastPoster ipsDataItem_withPhoto'>
			<li>		
                {template="userPhoto" app="core" group="global" params="$row->author(), 'tiny'"}
			</li>
			<li>
				{$row->author()->link()|raw}	
			</li>
			<li class="ipsType_light">
                {datetime="$row->__get( $row::$databaseColumnMap['date'] )" dateonly="true"}
			</li>
		</ul>                
		{{if $table->canModerate()}}
			<div class='ipsDataItem_modCheck ipsType_noBreak ipsPos_center'>
				<a href='#elTorrents{$row->tid}_menu' id='elTorrents{$row->tid}' class='ipsType_large ipsPos_middle ipsType_blendLinks' data-ipsMenu>
					<i class='fa fa-cog'></i> <i class='fa fa-caret-down'></i>
				</a>
                
				<input type='checkbox' data-role='moderation' name="moderate[{$row->tid}]" data-actions="{expression="implode( ' ', $table->multimodActions( $row ) )"}" data-state='{$row->tableStates()}'>

				<ul class='ipsMenu ipsMenu_auto ipsMenu_withStem ipsHide' id='elTorrents{$row->tid}_menu'>
					{{if $row->canEdit()}}				
						<li class='ipsMenu_item'><a href='{$row->url()->csrf()->setQueryString( array( 'do' => 'edit' ) )}' title='{lang="bitracker_edit_details_title"}'>{lang="bitracker_edit_details"}</a></li>
					{{endif}}
					{{if $row->canHide()}}				
						<li class='ipsMenu_item'><a href='{$row->url()->csrf()->setQueryString( array( 'do' => 'moderate', 'action' => 'hide' ) )}' title='{lang="hide_title_bitracker"}' data-ipsDialog data-ipsDialog-title="{lang="hide"}">{lang="hide"}</a></li>
					{{endif}}
					{{if $row->canUnhide()}}				
						<li class='ipsMenu_item'><a href='{$row->url()->csrf()->setQueryString( array( 'do' => 'moderate', 'action' => 'unhide' ) )}' title='{{if $row->hidden() === 1}}{lang="approve_title_bitracker"}{{else}}{lang="unhide_title_bitracker"}{{endif}}'>{{if $row->hidden() === 1}}{lang="approve"}{{else}}{lang="unhide"}{{endif}}</a></li>
					{{endif}}                          
					{{if $row->canFeature() AND !$row->featured}}				
						<li class='ipsMenu_item'><a href='{$row->url()->csrf()->setQueryString( array( 'do' => 'moderate', 'action' => 'feature' ) )}' title='{lang="feature_title_bitracker"}'>{lang="feature"}</a></li>
					{{endif}}
					{{if $row->canUnfeature() AND $row->featured}}				
						<li class='ipsMenu_item'><a href='{$row->url()->csrf()->setQueryString( array( 'do' => 'moderate', 'action' => 'unfeature' ) )}' title='{lang="unfeature_title_bitracker"}'>{lang="unfeature"}</a></li>
					{{endif}}
					{{if $row->canMove()}}				
						<li class='ipsMenu_item'><a href='{$row->url()->csrf()->setQueryString( array( 'do' => 'move' ) )}' data-ipsDialog data-ipsDialog-size='narrow' data-ipsDialog-title="{lang="move"}"  title='{lang="bitracker_move_title"}'>{lang="move"}</a></li>
					{{endif}}
					{{if $row->canChangeAuthor()}}
						<li class='ipsMenu_item'><a href='{$row->url()->setQueryString( array( 'do' => 'changeAuthor' ) )}' data-ipsDialog data-ipsDialog-size='narrow' data-ipsDialog-title="{lang="bitrackers_change_author"}" title='{lang="bitrackers_change_author"}'>{lang="bitrackers_change_author"}</a></li>
					{{endif}}
					{{if $row->canDelete()}}
                        <li class='ipsMenu_sep'></li>			
						<li class='ipsMenu_item'><a href='{$row->url()->csrf()->setQueryString( array( 'do' => 'moderate', 'action' => 'delete' ) )}' data-confirm  title='{lang="bitracker_delete_title"}'>{lang="delete"}</a></li>
					{{endif}}
				</ul>
			</div>
		{{endif}}                      
	</li>
{{endforeach}}