<ips:template parameters="$select, $pagination, $members" />

{{if trim( $pagination )}}
	{$pagination|raw}
	<br><br>
{{endif}}
{{if count( $select )}}
	<table class="ipsTable ipsTable_zebra">
		<thead>
			<tr>
				<th>{lang="member"}</th>
				<th>{lang="torrents"}</th>
			</tr>
		</thead>
		<tbody>
			{{foreach $select as $row}}
				{{$member = \IPS\Member::constructFromData( $members[ $row['dmid'] ] );}}
				<tr>
					<td>{template="userPhoto" app="core" group="global" params="$member"} {$member->name}</td>
					<td><a href='{url="app=bitracker&module=stats&controller=member&do=downloads&id={$member->member_id}&tab=downloads&&type%5Bd74394%5D=Table"}'>{$row['downloads']}</a></td>
				</tr>
			{{endforeach}}
		</tbody>
	</table>
	<br>

	{$pagination|raw}
{{else}}
	<p class="ipsPad">{lang="no_results"}</p>
{{endif}}